### ISSUE TITLE
Current parallels install from scratch expects `prlctl` to be pre-existing

### ISSUE THREAD

**Issue by webknjaz** [samdoran/ansible-collection-macos#40]
```console
TASK [samdoran.macos.parallels : Ensure the Parallels Desktop app is not running] **********************************************************************************************************************

fatal: [xxxxxxxxx-xx]: FAILED! => {"changed": false, "msg": "Failed to find required executable \"prlctl\" in paths: /usr/local/bin/:/usr/bin:/bin:/usr/sbin:/sbin"}
```

$sbj is happening on new host. There's probably several ways of addressing this:
- check if the executable is present somewhere; this requires hardcoding paths probably; the `samdoran.macos.parallels_desktop` module could return a successful outcome if it's requested to stop the process
- check if parallels is installed via `pkgutil` in the task file

For me, this sounds like a possible excuse to build modules around `pkgutil` (which would also help with #4 and #38).

**Comment by webknjaz** [comment]
Here's what it looks like when present:
```console
administrator@xxxxxxxxx-xx:~$ pkgutil --packages | grep -i parall
com.parallels.autodeploy.package
com.parallels.pkg.sdk
administrator@xxxxxxxxx-xx:~$ pkgutil --pkg-info=com.parallels.autodeploy.package
package-id: com.parallels.autodeploy.package
version: 19.2.0
volume: /
location: 
install-time: 1707501721
administrator@xxxxxxxxx-xx:~$ pkgutil --pkg-info=com.parallels.pkg.sdk
package-id: com.parallels.pkg.sdk
version: 19.2.1.54832
volume: /
location: /
install-time: 1707506140
```

**Comment by samdoran** [comment]
I like the idea of using `pkgutil` to see if the package is installed. The identifier is pretty stable, so checking for `com.parallels.pkg.sdk` is probably reliable.

There are `--lsbom` and `--files` options if we feel the need to inspect the files in the package.
